[SMTP_SERVER]
# Server address for the SMTP Server
server = smtpserverexample.com
# Usually 465 with SSL and 587 with STARTTLS
port = 587
# The delay in seconds between sending emails for throttling the SMTP server
delay_between_emails_seconds = 10
# Set to 'true' if you prefer SSL; default is 'false' for STARTTLS
use_ssl = false

[AUTHENTICATION]
# Username for the SMTP Server used to log in
username = username@smtpserverexample.com
# Password of the user for the SMTP Server used to log in
password = smtppassword

[SUBJECT_AND_SENDER]
# Full name of the sender
sender_name = John Doe     
# Email address of the sender, usually the same as the username
sender_email = username@smtpserverexample.com  
